// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAvUEQPevF-69vR9Yi1WdDqButkuV-pgg',
    appId: '1:510248772086:web:a08dbe03ec3e07944327d7',
    messagingSenderId: '510248772086',
    projectId: 'musclemate-386814',
    authDomain: 'musclemate-386814.firebaseapp.com',
    storageBucket: 'musclemate-386814.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFpZLJgpb273VFRTpwhjnCb49-22OaOnU',
    appId: '1:510248772086:android:2e1a6007b53eb1ff4327d7',
    messagingSenderId: '510248772086',
    projectId: 'musclemate-386814',
    storageBucket: 'musclemate-386814.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzwrbkSshRsUB4IWOpQ0O8m49uxzR35Qc',
    appId: '1:510248772086:ios:ca9ce541447931dc4327d7',
    messagingSenderId: '510248772086',
    projectId: 'musclemate-386814',
    storageBucket: 'musclemate-386814.appspot.com',
    androidClientId: '510248772086-u4v8sjg6aaapucc8dh13jf2fpvo3a4km.apps.googleusercontent.com',
    iosClientId: '510248772086-ga7ucj58bs2ccildupdcara1e272cvtm.apps.googleusercontent.com',
    iosBundleId: 'com.example.musclemate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzwrbkSshRsUB4IWOpQ0O8m49uxzR35Qc',
    appId: '1:510248772086:ios:ca9ce541447931dc4327d7',
    messagingSenderId: '510248772086',
    projectId: 'musclemate-386814',
    storageBucket: 'musclemate-386814.appspot.com',
    androidClientId: '510248772086-u4v8sjg6aaapucc8dh13jf2fpvo3a4km.apps.googleusercontent.com',
    iosClientId: '510248772086-ga7ucj58bs2ccildupdcara1e272cvtm.apps.googleusercontent.com',
    iosBundleId: 'com.example.musclemate',
  );
}
